server:
  port: 8086

spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: YOUR_MAILTRAP_USERNAME
    password: YOUR_MAILTRAP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

shopflow:
  internal-key: ${SHOPFLOW_INTERNAL_KEY:shopflow-internal-secure-key-2026}
