server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:ShopFlowDefaultJwtSecretKeyForDev2026Base64StringLengthMinimum256Bits!}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:YOUR_STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:YOUR_STRIPE_WEBHOOK_SECRET}

shopflow:
  internal-key: ${SHOPFLOW_INTERNAL_KEY:shopflow-internal-secure-key-2026}
